### ISSUE TITLE
Partial-eta-squared for the whole factor vs contrasts

### ISSUE THREAD

**Issue by matschmitz** [bcjaeger/r2glmm#16]
Would be nice to have the possibility to have the effect sizes for the whole factor and for the dummy codes.

Showcase here:
https://stats.stackexchange.com/questions/574997/lmer-anova-effect-sizes

**Comment by bcjaeger** [comment]
I agree, I think this should be an option the user can pick from. I plan on putting an update on CRAN at some point in the future with this feature. Thank you for posting!

**Comment by alexisdmacintyre** [comment]
Hi @bcjaeger , I see this issue is marked as completed but it's not clear to me whether it was ever implemented? If so, can you advise on how to choose to see the dummy codes? Thanks!

**Comment by bcjaeger** [comment]
Hello! I apologize for the awkwardness of it, but you can get partial R2 for an entire factor if you are using the dev version of `r2glmm` and you can get partial R2 for each factor level separately if you are using the current version on CRAN. If you need both, you may just check out the code [here](https://github.com/bcjaeger/r2glmm/blob/924c0206969e70999d09b34a743eb85ec166b5fd/R/r2beta_lmerMod_Function.R#L121C1-L148C56) and modify it to get both single factor levels and a grouped summary.

**Comment by alexisdmacintyre** [comment]
Ah, I see. I tried the current CRAN version and also attempted an earlier version using `remote()` but they returned the same results for me (as dev). Looking at the code you linked, my understanding is that the list of effect sizes returned is based on `stats::terms(model)`. Calling this with my model returns the same grouped factor (instead of the lme4 readout, which is broken down by factor level).   I'm not sure if I need to do some kind of dummy coding or what to force the matter further, but it seems like the issue is outside of `r2beta`. Thanks for the help!
