### ISSUE TITLE
Partial correlations for random effects - possible or sensible?

### ISSUE THREAD

**Issue by jrosen48** [bcjaeger/r2glmm#5]
Hi, thanks for a helpful and easy-to-use package. **r2glmm** can output the semi-partial R-squared values for specific fixed-effects predictors. Is it possible - and does it make sense - to do the same for specific random effects? Can these be calculated simply as the square of the intra-class correlation?

**Comment by bcjaeger** [comment]
Thank you for being patient. I was very slow at responding to this. r2glmm makes semi-partial values for R2 statistics based on Wald tests for groups of fixed effects in the model. It has been awhile since I've worked with mixed models, but I am not aware of a reliable way to conduct Wald tests for random effects. A critical issue is that the parameter space for covariance terms does not include all real numbers (i.e., variance is > 0).
